language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - pip install nose --use-mirrors
before_script:
    - cp ./tests/example_config ./tests/config
# command to run tests
script: nosetests tests.tests_unit tests.test_client