language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - pip install nose
before_script:
  - cp ./tests/example_config ./tests/config
# command to run tests
script: nosetests -w tests/
notifications:
  email:
    - api@shotgunsoftware.com
