language: python
python:
  - "2.6"
  - "2.7"

# use trusty dist, since xenial (default) does not support python 2.6
dist: trusty

# command to install dependencies
install:
  - pip install -r tests/ci_requirements.txt
before_script:
  - cp ./tests/example_config ./tests/config
# command to run tests
script: coverage run -m nose
after_success: coveralls
notifications:
  email:
    - api@shotgunsoftware.com
