language: python

# We need to test on multiple distros, since python 2.6 is not supported in xenial
# and 3.7 is not supported in trusty.  For now just use trusty to test 2.6, and use
# the more modern xenial for 2.7 and 3.7.
matrix:
  include:
    # use trusty dist, since xenial (default) does not support python 2.6
    - dist: trusty
      python: "2.6"
      env: RUN_FLAKE=false
    # test python 2.7 and 3.7 on xenial.
    - dist: xenial
      python: "2.7"
      env: RUN_FLAKE=true
    - dist: xenial
      python: "3.7"
      env: RUN_FLAKE=true

# command to install dependencies
install:
  - pip install -r tests/ci_requirements.txt
before_script:
  - cp ./tests/example_config ./tests/config
# Run flake and then run tests
script:
  # flake8 does not support python 2.6, so only run it on 2.7+
  - if [ -n "$RUN_FLAKE" = true ]; then flake8; fi
  - coverage run -m nose --config="nose.cfg"
after_success: coveralls
notifications:
  email:
    - api@shotgunsoftware.com
